- type: job
  id: Psychiatrist
  name: job-name-psychiatrist
  description: job-description-psychiatrist
  playTimeTracker: JobPsychiatrist
  requirements:
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 14400 #4 hrs
    - !type:OverallPlaytimeRequirement
      time: 54000 # 15 hrs
  startingGear: PsychiatristGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Chemistry

- type: startingGear
  id: PsychiatristGear
  equipment:
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
  satchel: ClothingBackpackSatchelMedicalFilled
  duffelbag: ClothingBackpackDuffelMedicalFilled
  #storage:
    #back:
    #- stuff
