- type: job
  id: Bartender
  name: job-name-bartender
  description: job-description-bartender
  playTimeTracker: JobBartender
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 7200 #2 hrs # Orienta-RoleTime
  startingGear: BartenderGear
  icon: "JobIconBartender"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Bar
  extendedAccess:
  - Kitchen
  - Hydroponics
  # Orienta skills - start
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skills
        skills:
          Guns: 0.5
          Melee: 0.1
  # Orienta skills - end

- type: startingGear
  id: BartenderGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: BartenderPDA
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff
