- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 216000 #60 hrs
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-rd
  jobEntity: PlayerBorgGeneric
  # Orienta skills - start
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skills
        anySkills: true
  # Orienta skills - end
